from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol

from novelwiki.modules.identity.public import Principal

from ..public import SourceDraft


class ScraperAdapterCatalog(Protocol):
    def list_adapters(self) -> list[dict]: ...


@dataclass(frozen=True)
class AssetFile:
    path: Path
    mime: str


@dataclass(frozen=True)
class ImportAssetOwner:
    user_id: int | None
    detected_meta: dict[str, Any]


class CatalogAccessPort(Protocol):
    async def require_readable(self, novel_id: int, principal: Principal) -> None: ...
    async def require_editable(self, novel_id: int, principal: Principal) -> None: ...


class SourceUrlPort(Protocol):
    async def validate(self, url: str) -> str: ...


class SourceOffsetPort(Protocol):
    async def update(self, source_id: int, offset: float) -> int: ...


class SpendPolicyPort(Protocol):
    def ensure_allowed(self, principal: Principal) -> None: ...
    async def reserve_ocr(self, principal: Principal, pages: int) -> None: ...


class ScrapeWorkPort(Protocol):
    async def schedule(
        self, *, novel_id: int, user_id: int, options: dict, idempotency_key: str
    ) -> tuple[int, bool]: ...


class AcquisitionRepository(Protocol):
    async def create_source(self, novel_id: int, draft: SourceDraft) -> int: ...
    async def source_exists(self, novel_id: int, source_id: int) -> bool: ...
    async def update_source(
        self, source_id: int, fields: dict[str, object]
    ) -> int: ...
    async def novel_asset(
        self, novel_id: int, sha256: str, relative_path: str
    ) -> tuple[str, str | None] | None: ...
    async def import_asset_owner(self, job_id: int) -> ImportAssetOwner | None: ...


class AssetFilesystemPort(Protocol):
    def normalize_filename(self, filename: str) -> tuple[str, str, str]: ...
    def novel_relative_path(self, novel_id: int, sha256: str, extension: str) -> str: ...
    def novel_file(
        self, novel_id: int, safe_name: str, mime: str | None
    ) -> AssetFile: ...
    def staged_file(self, job_id: int, safe_name: str) -> AssetFile: ...


class ImportGateway(Protocol):
    async def create_job(self, format: str, **fields) -> int: ...
    async def get_job(self, job_id: int) -> dict | None: ...
    async def list_jobs(self, user_id: int | None) -> list[dict]: ...
    async def update_job(self, job_id: int, **fields) -> None: ...
    async def delete_job(self, job_id: int) -> None: ...
    async def duplicate_imports(self, sha256: str, job_id: int) -> list[dict]: ...
    async def source_novel_id(self, source_id: int) -> int | None: ...
    async def save_upload(self, job_id: int, upload, extension: str, max_bytes: int): ...
    def cleanup_job(self, job_id: int) -> None: ...
    def init_upload(self, job_id: int, extension: str) -> Path: ...
    def upload_offset(self, job_id: int, extension: str) -> int: ...
    def chunk_matches(self, job_id: int, extension: str, offset: int, data: bytes) -> bool: ...
    def write_chunk(self, job_id: int, extension: str, offset: int, data: bytes) -> int: ...
    def finalize_upload(self, job_id: int, extension: str) -> tuple[str, int]: ...
    async def touch_job(self, job_id: int) -> None: ...
    def import_files(self, root: str, recursive: bool) -> list[tuple[str, str]]: ...
    def ensure_dirs(self) -> None: ...
    def copy_original(self, job_id: int, source: str, extension: str): ...
    def is_directory(self, root: str) -> bool: ...
    def block_count(self, job_id: int) -> int | None: ...
    async def commit_series(self, job_ids: list[int]) -> dict: ...
