"""Composition-injected capabilities used by Acquisition runtimes."""

from __future__ import annotations

from typing import Any, Protocol


class AcquisitionRuntimePort(Protocol):
    async def import_repository(self): ...
    async def owner_can_spend(self, user_id: int) -> bool: ...
    async def novel_titles(self, novel_ids: set[int]) -> dict[int, str]: ...
    async def gemini_budget_remaining(self) -> int: ...
    async def commit_uow_factory(self): ...
    async def reserve_auto_codex(self, user_id: int) -> bool: ...
    async def schedule_codex(
        self, novel_id: int, start: float, end: float, user_id: int | None
    ) -> None: ...
    async def import_job(self, job_id: int) -> dict | None: ...
    async def upsert_ingested_chapter(
        self, source: dict, number: float, chapter: Any, force: bool
    ) -> bool: ...
    async def resume_url(self, source_id: int) -> str | None: ...
    async def update_source_offset(self, source_id: int, offset: float) -> int: ...
    async def call_llm(self, *args, **kwargs): ...
    async def call_vision(self, *args, **kwargs): ...
    def ensure_import_dirs(self) -> None: ...
    def save_blocks(self, job_id: int, document: Any) -> None: ...
    def staged_asset_url(self, job_id: int, sha: str, extension: str) -> str: ...
    def cleanup_import_job(self, job_id: int) -> None: ...
    def parse_epub(self, path: str, job_id: int): ...
    def parse_pdf_text(self, path: str, job_id: int): ...
    def build_segment_plan(self, document: Any) -> dict: ...
    async def refine_segment_plan(self, plan: dict, document: Any) -> dict: ...
    async def commit_series(self, job_ids: list[int]) -> dict: ...
    def estimate_ocr_cost(self, pages: int, gemini_first: bool, remaining: int) -> dict: ...
    async def parse_pdf_ocr(self, path: str, job_id: int, options: dict, progress): ...
    async def commit_job(self, job: dict) -> dict: ...
