from __future__ import annotations

import datetime as dt
from typing import Protocol


class QuotaRepository(Protocol):
    async def get_usage(self, user_id: int, period: dt.date) -> dict[str, int]: ...
    async def bump(self, user_id: int, period: dt.date, kind: str, units: int) -> None: ...
    async def try_reserve(
        self, user_id: int, period: dt.date, kind: str, units: int, limit: int
    ) -> bool: ...
    async def refund(
        self, user_id: int, period: dt.date, kind: str, units: int
    ) -> int: ...


class SessionRepository(Protocol):
    async def load_active_user(self, token_hash: str) -> dict | None: ...


class TokenHasher(Protocol):
    def __call__(self, token: str) -> str: ...


class DuplicateRegistration(Exception):
    def __init__(self, field: str):
        self.field = field
        super().__init__(field)


class AuthPersistence(Protocol):
    async def consume_rate(self, key: str, limit: object) -> None: ...
    async def ensure_rate(self, key: str, limit: object) -> None: ...
    async def clear_rate(self, key: str) -> None: ...
    async def register_user(
        self, email: str, username: str, password_hash: str, token: str,
        expires_at: dt.datetime, user_agent: str | None,
    ) -> tuple[dict, str]: ...


class AuthRuntime(Protocol):
    def new_token(self, nbytes: int = 32) -> str: ...
    def hash_token(self, token: str) -> str: ...
    def hash_password(self, password: str) -> str: ...
    def verify_password(self, stored_hash: str | None, password: str) -> bool: ...
    def sign(self, value: str) -> str: ...
    def unsign(self, signed: str, max_age: int | None = None) -> str | None: ...
    def stamped(self, value: str) -> str: ...
    def configured_providers(self) -> list[str]: ...
    def is_provider_configured(self, provider: str) -> bool: ...
    def authorize_url(self, provider: str, state: str) -> str: ...
    async def exchange_code(self, provider: str, code: str) -> dict: ...
    async def send_verification_email(self, to: str, link: str) -> None: ...
    async def send_reset_email(self, to: str, link: str) -> None: ...


class AvatarStorage(Protocol):
    def save(self, user_id: int, data: bytes, extension: str) -> str: ...
    async def find_login_user(self, identifier: str) -> dict | None: ...
    async def create_user_session(self, user_id: int, user_agent: str | None) -> str: ...
    async def revoke_session(self, token: str) -> None: ...
    async def linked_providers(self, user_id: int) -> list[str]: ...
    async def change_password(
        self, user_id: int, password_hash: str, user_agent: str | None,
    ) -> str: ...
    async def verification_token_valid(self, token_hash: str) -> bool: ...
    async def issue_reset_token(
        self, email: str, token: str, expires_at: dt.datetime,
    ) -> bool: ...
    async def reset_password(self, token_hash: str, password_hash: str) -> bool: ...
    async def confirm_verification(self, token_hash: str) -> bool: ...
    async def oauth_login(
        self, provider: str, identity: dict, user_agent: str | None,
    ) -> tuple[dict, str]: ...
