from __future__ import annotations

from typing import Protocol

from novelwiki.modules.catalog.public import NovelAccess, NovelDraft, TagSuggestionRecord


class CatalogRepository(Protocol):
    async def get_access(self, novel_id: int) -> NovelAccess | None: ...
    async def add_to_library(self, novel_id: int, user_id: int) -> None: ...
    async def remove_from_library(self, novel_id: int, user_id: int) -> None: ...
    async def set_visibility(
        self, novel_id: int, visibility: str, steward_id: int | None = None
    ) -> None: ...
    async def set_shelf(
        self, novel_id: int, user_id: int, shelf: str | None
    ) -> None: ...
    async def update_metadata(self, novel_id: int, fields: dict) -> None: ...
    async def create_novel(self, draft: NovelDraft, owner_id: int) -> int: ...
    async def delete_novel(self, novel_id: int) -> None: ...
    async def create_tag_suggestion(
        self, novel_id: int, from_user_id: int, tags: list[str], note: str | None
    ) -> int: ...
    async def list_tag_suggestions(
        self, novel_id: int, status: str
    ) -> list[TagSuggestionRecord]: ...
    async def get_tag_suggestion(
        self, novel_id: int, suggestion_id: int
    ) -> tuple[list[str], str] | None: ...
    async def apply_tags(self, novel_id: int, tags: list[str]) -> None: ...
    async def review_tag_suggestion(
        self, suggestion_id: int, status: str, reviewed_by: int
    ) -> bool: ...
