from __future__ import annotations

from typing import Protocol

from novelwiki.modules.catalog.public import NovelAccess


class CatalogRepository(Protocol):
    async def get_access(self, novel_id: int) -> NovelAccess | None: ...
    async def add_to_library(self, novel_id: int, user_id: int) -> None: ...
    async def remove_from_library(self, novel_id: int, user_id: int) -> None: ...
    async def set_visibility(
        self, novel_id: int, visibility: str, steward_id: int | None = None
    ) -> None: ...
    async def set_shelf(
        self, novel_id: int, user_id: int, shelf: str | None
    ) -> None: ...
    async def update_metadata(self, novel_id: int, fields: dict) -> None: ...
