from __future__ import annotations

from typing import Protocol


class AgyWorkerStateRepository(Protocol):
    async def write_heartbeat(self, **fields) -> None: ...
    async def orphan_runs(self) -> list[dict]: ...
    async def mark_orphan_lost(self, run_id: int) -> None: ...
    async def acquire_subscription_lock(self, key: str) -> bool: ...
    async def release_subscription_lock(self, key: str) -> None: ...


class AgyIdentityPort(Protocol):
    async def load_user(self, user_id: int) -> dict | None: ...


class AgyReadingRecoveryPort(Protocol):
    async def reset_staged_translations(self, run_id, status: str) -> int: ...


class AgyWorkPort(Protocol):
    async def active_job_count(self, user_id: int) -> int: ...
    async def fallback_to_api(
        self, job_id: int, model: str, max_attempts: int, error: str
    ) -> bool: ...
