from __future__ import annotations

from typing import Protocol

from novelwiki.modules.identity.public import Principal

from .dto import Bookmark, Progress


class CatalogReadAccess(Protocol):
    async def require_readable(
        self, novel_id: int, principal: Principal | None
    ) -> object: ...


class ReadingRepository(Protocol):
    async def get_progress(self, novel_id: int, user_id: int) -> Progress: ...
    async def chapter_exists(self, novel_id: int, chapter: float) -> bool: ...
    async def set_progress(self, novel_id: int, user_id: int, chapter: float, scroll_pct: float) -> None: ...
    async def list_bookmarks(self, novel_id: int, user_id: int) -> list[Bookmark]: ...
    async def add_bookmark(self, novel_id: int, user_id: int, chapter: float, note: str | None) -> int: ...
    async def delete_bookmark(self, novel_id: int, user_id: int, bookmark_id: int) -> None: ...
    async def chapter_span(self, novel_id: int) -> tuple[int, float | None, float | None]: ...
    async def trusted_ceiling(self, novel_id: int, user_id: int) -> float | None: ...
