from __future__ import annotations

from typing import Protocol

from .application.dto import Bookmark, Progress


class ReadingApi(Protocol):
    async def get_progress(self, novel_id: int, user_id: int) -> Progress: ...
    async def set_progress(self, novel_id: int, user_id: int, chapter: float, scroll_pct: float) -> None: ...
    async def list_bookmarks(self, novel_id: int, user_id: int) -> list[Bookmark]: ...
    async def add_bookmark(self, novel_id: int, user_id: int, chapter: float, note: str | None) -> int: ...
    async def delete_bookmark(self, novel_id: int, user_id: int, bookmark_id: int) -> None: ...
