from __future__ import annotations

from typing import Protocol

from novelwiki.modules.identity.public import Principal


class NarrationAccessPort(Protocol):
    async def require_readable(self, novel_id: int, principal: Principal) -> None: ...


class ChapterTextPort(Protocol):
    async def resolve(self, novel_id: int, chapter: float, user_id: int) -> dict: ...


class NarrationQuotaPort(Protocol):
    async def check_available(self, principal: Principal, units: int = 1) -> None: ...


class NarrationQueryPort(Protocol):
    async def book_candidates(
        self, novel_id: int, voice: str, start: float | None, end: float | None
    ) -> list[dict]: ...
    async def shared_audio_chapters(self, novel_id: int, voice: str) -> list[float]: ...
    async def available_voices(
        self, novel_id: int, chapter: float, content_version: int,
        user_id: int | None,
    ) -> list[str]: ...
    async def coverage(self, novel_id: int) -> dict: ...


class NarrationJobsPort(Protocol):
    async def find_audio(
        self, novel_id: int, chapter: float, voice: str,
        content_version: int, user_id: int | None,
    ) -> dict | None: ...
    async def find_active_chapter_job(
        self, novel_id: int, chapter: float, voice: str,
        content_version: int, user_id: int | None,
    ) -> dict | None: ...
    async def find_active_book_job(self, novel_id: int, voice: str) -> dict | None: ...
    def chapter_options(
        self, novel_id: int, chapter: float, voice: str,
        content_version: int, user_id: int | None, force: bool,
    ) -> dict: ...
    async def create_job(
        self, novel_id: int, user_id: int, scope: str, voice: str, options: dict
    ) -> int: ...
    async def get_job(self, job_id: int) -> dict | None: ...
    async def cancel_job(self, job_id: int) -> None: ...
    async def lookup_for_reader(
        self, novel_id: int, chapter: float, voice: str, user_id: int
    ) -> dict | None: ...
    def absolute_audio_path(self, relative_path: str) -> str: ...


class NarrationSidecarPort(Protocol):
    async def list_voices(self) -> list[dict]: ...


class AudioFilePort(Protocol):
    def exists(self, path: str) -> bool: ...


class NarrationWorkerRepository(Protocol):
    async def create_job(
        self, novel_id: int, user_id: int | None, scope: str,
        voice_id: str, options: dict, active_statuses: tuple[str, ...],
    ) -> int: ...
    async def get_job(self, job_id: int) -> dict | None: ...
    async def active_chapter_job(self, **criteria) -> dict | None: ...
    async def active_book_job(
        self, novel_id: int, voice_id: str, active_statuses: tuple[str, ...]
    ) -> dict | None: ...
    async def update_job(self, job_id: int, fields: dict) -> None: ...
    async def cancel_job(self, job_id: int) -> None: ...
    async def status(self, job_id: int) -> str | None: ...
    async def find_audio(self, **criteria) -> dict | None: ...
    async def upsert_audio(self, **audio) -> None: ...
    def target_lock(self, key: str): ...
    async def requeue_interrupted(self) -> str: ...
    async def claim_next(self, trigger_statuses: tuple[str, ...]) -> dict | None: ...


class NarrationWorkerIdentityPort(Protocol):
    async def load_user(self, user_id: int) -> dict | None: ...
